//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleIM.Data
{
    using System;
    
    public enum ContactInformationTypes : byte
    {
        PhoneNumber = 0,
        Email = 1,
        SkypeId = 2,
        ExtensionNumber = 3
    }
}
