//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleIM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.ContactInformation = new HashSet<ContactInformation>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<byte> Image { get; set; }
        public string FName { get; set; }
        public string SName { get; set; }
        public string SSName { get; set; }
        public string DateOfBirth { get; set; }
    
        public virtual Location Locations { get; set; }
        public virtual Room Rooms { get; set; }
        public virtual Company Companies { get; set; }
        public virtual Department Departments { get; set; }
        public virtual ICollection<ContactInformation> ContactInformation { get; set; }
        public virtual Position Positions { get; set; }
    }
}
