//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleIM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Task()
        {
            this.Event = new HashSet<Event>();
        }
    
        public int Id { get; set; }
        public TaskTypes TaskType { get; set; }
        public ISTypes Source { get; set; }
        public string Data { get; set; }
    
        public virtual ICollection<Event> Event { get; set; }
        public virtual InformationSystem Destination { get; set; }
    }
}
