//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleIM.Data
{
    using System;
    
    public enum TaskTypes : byte
    {
        CreateUser = 0,
        DeleteUser = 1,
        DenyAccess = 2,
        PermitAccess = 3,
        BlockUser = 4
    }
}
