//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleIM.Data
{
    using System;
    
    public enum TaskStates : byte
    {
        Created = 0,
        InProcessing = 1,
        Completed = 2,
        Terminated = 3
    }
}
